name: CI - Node.JS

on:
  push:
    branches: [ master ]

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello_world
        run: echo "Hello World!"

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Finish job
        run: echo "Finish Job"