name: CI - Node.JS

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  NODE_BUILD_VERSION: 22
  NODE_KEY: ${{ vars.KEY }}

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_BUILD_VERSION }}
          cache: npm

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    needs: Lint

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node-version }}
          path: coverage/
          if-no-files-found: ignore

  Build:
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.JS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_BUILD_VERSION }}
          cache: npm

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build


  Environment:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Print var
        run: echo ${{ vars.KEY }}