name: Setup Node
description: Checkout + setup Node + install dependencies

inputs:
  node-version:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - run: npm ci
      shell: bash